### ISSUE TITLE
[Bug]: Dungeon crasht bei bestimmten Befehlen

### ISSUE THREAD

**Issue by FabiKl** [MUD-Game/HouseOfMUD#224]
### What happened?

Wenn man einen Befehl sendet, welcher wie ein echter Befehl anfängt, aber nicht dem Befehl entspricht crasht der Dungeon.
z.B. **sag**asfdfhdsdf, **gehe**n

### Location

Host

### Relevant log output

```shell
D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\action\action-handler.js:111
        action.performAction(user, actionArguments);
               ^

TypeError: Cannot read properties of undefined (reading 'performAction')
    at ActionHandlerImpl.processAction (D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\action\action-handler.js:111:16)
    at DungeonController.<anonymous> (D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:96:40)
    at Generator.next (<anonymous>)
    at D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:4:12)
    at DungeonController.handleAmqpMessages (D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:87:16)
    at DungeonController.<anonymous> (D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:50:30)
    at Generator.next (<anonymous>)
    at D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:4:12)
    at D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\controller\dungeon-controller.js:45:54
    at D:\Docker\House of MUD\HouseOfMUD\backend\game\dist\src\worker\amqp\amqp-adapter.js:286:29
    at Channel.BaseChannel.dispatchMessage (D:\Docker\House of MUD\HouseOfMUD\backend\game\node_modules\amqplib\lib\channel.js:484:12)
    at Channel.BaseChannel.handleDelivery (D:\Docker\House of MUD\HouseOfMUD\backend\game\node_modules\amqplib\lib\channel.js:493:15)
Dungeon 62780b3990e7e9386de83d8e exited with code 1
```

**Comment by Sperlin** [comment]
Fixed by not using regexes for static commands
